#!/usr/bin/env node
// Merges skill output (corpus/) into prototype/corpus.js for the static prototype.
// Usage: node scripts/build-feed.mjs [--profile ananya] [--hold <opportunity-id>]
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const arg = (name, dflt) => {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? dflt : process.argv[i + 1];
};
const readJson = (p) => JSON.parse(readFileSync(p, 'utf8'));

const slug = arg('profile', 'ananya');
const hold = arg('hold', null);
const profile = readJson(join(root, 'corpus', 'profiles', `${slug}.json`));

const oppDir = join(root, 'corpus', 'opportunities');
const briefDir = join(root, 'corpus', 'briefs', profile.id);

const BRIEF_FIELDS = ['priority', 'fit', 'why_go', 'watch_out', 'tagline', 'eligible', 'eligibility_notes',
  'visa', 'explore', 'explore_reason', 'confidence', 'cost_estimate', 'funding'];

const merged = [];
const skipped = [];
for (const f of readdirSync(oppDir).filter((f) => f.endsWith('.json'))) {
  const opp = readJson(join(oppDir, f));
  const briefPath = join(briefDir, f);
  if (!existsSync(briefPath)) { skipped.push(opp.id); continue; }
  const brief = readJson(briefPath);
  const out = { ...opp, venue_funding: opp.funding ?? [] };
  for (const k of BRIEF_FIELDS) if (brief[k] !== undefined) out[k] = brief[k];
  out.funding ??= [];
  const norm = (v, dflt) => {
    const s = String(v ?? '').toLowerCase();
    if (/infer|estimat|unverif|not verif|partial/.test(s)) return 'inferred';
    if (/verif|ground/.test(s)) return 'verified';
    if (/range/.test(s)) return 'range';
    if (/advis/.test(s)) return 'advisory';
    return dflt;
  };
  const c = out.confidence ?? {};
  out.confidence = { dates: norm(c.dates, 'inferred'), fees: norm(c.fees, 'inferred'), cost: 'range', visa: 'advisory',
    eligibility: norm(c.eligibility, 'inferred') };
  merged.push(out);
}

let groundedTotal = 0;
let groundedPass = 0;
for (const f of readdirSync(oppDir).filter((f) => f.endsWith('.json'))) {
  const o = readJson(join(oppDir, f));
  for (const item of [...(o.deadlines ?? []), ...(o.fees ?? []), ...(o.funding ?? []), ...(o.standing_signals ?? [])]) {
    if (item.grounded || item.verify_note) groundedTotal++;
    if (item.grounded) groundedPass++;
  }
}

const candidatesPath = join(root, 'corpus', 'candidates.json');
const candidates = existsSync(candidatesPath) ? readJson(candidatesPath) : { candidates: [], budget_used: {} };
const fxPath = join(root, 'corpus', 'fx.json');
const fx = existsSync(fxPath) ? readJson(fxPath) : {};

const heldBack = hold ? merged.find((o) => o.id === hold) ?? null : null;
const opportunities = merged.filter((o) => o !== heldBack);

const meta = {
  fields: profile.fields?.length ?? 0,
  adjacent: profile.adjacent_fields?.length ?? 0,
  searches: candidates.budget_used?.searches ?? 0,
  candidates: candidates.candidates?.length ?? 0,
  extracted: merged.length,
  funding: merged.reduce((n, o) => n + (o.funding?.length ?? 0), 0),
  grounded_pass: groundedPass,
  grounded_total: groundedTotal,
};

const GATHERED_AT = (candidates.generated_at ?? new Date().toISOString()).slice(0, 10);

const js = `// GENERATED by scripts/build-feed.mjs from corpus/ — do not edit by hand.
export const GATHERED_AT = ${JSON.stringify(GATHERED_AT)};
export const meta = ${JSON.stringify(meta, null, 2)};
export const FX = ${JSON.stringify(fx, null, 2)};
export const profile = ${JSON.stringify(profile, null, 2)};
export const heldBack = ${JSON.stringify(heldBack, null, 2)};
export const opportunities = ${JSON.stringify(opportunities, null, 2)};
`;
writeFileSync(join(root, 'prototype', 'corpus.js'), js);
console.log(`corpus.js: ${opportunities.length} opportunities${heldBack ? ` + 1 held back (${heldBack.id})` : ''}; ` +
  `grounded ${groundedPass}/${groundedTotal}; skipped (no brief): ${skipped.join(', ') || 'none'}`);
