#!/usr/bin/env node
// Bundles the SKILL.md files (and the registries they rely on) into api/_lib/prompts.js,
// so the live API uses exactly the same instructions as the Claude Code skills.
// Rerun after editing any skill: node scripts/build-prompts.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const skill = (name) => readFileSync(join(root, '.claude', 'skills', name, 'SKILL.md'), 'utf8')
  .replace(/^---[\s\S]*?---\s*/, '').trim();

const out = {
  draftProfile: skill('draft-profile'),
  scout: skill('scout-opportunities'),
  extract: skill('extract-opportunity'),
  estimateCost: skill('estimate-cost'),
  findFunding: skill('find-funding'),
  composeBrief: skill('compose-brief'),
};
const funders = JSON.parse(readFileSync(join(root, 'corpus', 'funders', 'india.json'), 'utf8'));
const fx = JSON.parse(readFileSync(join(root, 'corpus', 'fx.json'), 'utf8'));

mkdirSync(join(root, 'api', '_lib'), { recursive: true });
writeFileSync(join(root, 'api', '_lib', 'prompts.js'),
  `// GENERATED by scripts/build-prompts.mjs from .claude/skills and corpus/ — do not edit by hand.
export const SKILLS = ${JSON.stringify(out, null, 2)};
export const FUNDERS = { India: ${JSON.stringify(funders)} };
export const FX = ${JSON.stringify(fx)};
`);
console.log(`prompts.js: ${Object.keys(out).length} skills, ${funders.funders?.length ?? 0} India funders, FX as of ${fx.as_of}`);
