/**
 * Grapevine prototype — data layer.
 *
 * Opportunities and the persona are REAL skill output, not hand-written fixtures:
 * corpus.js is generated by scripts/build-feed.mjs from corpus/ (produced by the
 * skills in .claude/skills/). This file adds the UI-only vocabularies.
 */

import { GATHERED_AT, profile, opportunities, heldBack, FX, meta } from './corpus.js';

export { GATHERED_AT, profile, opportunities, heldBack, FX, meta };

export const TODAY = new Date(new Date().toISOString().slice(0, 10) + 'T00:00:00Z');

/** Steps shown in the "agent at work" animation, with the real counts from the last skill run. */
export const pipeline = [
  { label: 'Draft profile', detail: `${meta.fields} fields + ${meta.adjacent} adjacent fields inferred from your description`, ms: 800 },
  { label: 'Scout — society graph, literature, recurrence', detail: `${meta.searches} searches · ${meta.candidates} candidates found`, ms: 1100 },
  { label: `Extraction ×${meta.extracted}`, detail: 'one call page each, every deadline quoted from the source', ms: 1100 },
  { label: 'Funding + cost', detail: `${meta.funding} funding routes · costs in ${profile.currency}`, ms: 900 },
  { label: 'Is it worth going?', detail: 'fit · standing · network · outcomes · feasibility, weighted by your goals', ms: 900 },
  { label: 'Verification', detail: `${meta.grounded_pass} of ${meta.grounded_total} quoted facts still ✓ after re-checking the source pages`, ms: 700 },
];

/** What someone might want out of an opportunity. Each goal shifts the priority weights. */
export const GOALS = [
  { id: 'networking', label: 'Meet people', sub: 'Who you would meet', emoji: '🤝' },
  { id: 'publication', label: 'Get published', sub: 'A route into print', emoji: '📄' },
  { id: 'visibility', label: 'A well-known venue', sub: 'A line that counts on a CV', emoji: '🏛' },
  { id: 'low_cost', label: 'Keep it affordable', sub: 'Cost and visa matter most', emoji: '💸' },
  { id: 'feedback', label: 'Feedback on my work', sub: 'Workshops, respondents', emoji: '💬' },
];

/** Browsable topic list for onboarding, grouped by field. `k` = keywords matched in free text. */
export const topicVocabulary = [
  { field: 'South Asian studies', topics: [
    { term: 'caste & digital media', k: ['caste', 'dalit', 'bahujan', 'jati'] },
    { term: 'Dalit & Bahujan counterpublics', k: ['dalit', 'bahujan', 'ambedkar', 'counterpublic'] },
    { term: 'Partition memory', k: ['partition', '1947'] },
    { term: 'South Asian diaspora', k: ['diaspora', 'migrant', 'nri'] },
    { term: 'Hindi & regional-language cinema', k: ['cinema', 'bollywood', 'film', 'tamil', 'telugu'] },
    { term: 'gender & sexuality in South Asia', k: ['gender', 'queer', 'feminis', 'sexuality'] },
    { term: 'religion & politics in India', k: ['hindutva', 'religio', 'communal', 'muslim'] },
  ] },
  { field: 'Media & communication', topics: [
    { term: 'creator cultures & influencers', k: ['creator', 'influencer', 'youtube', 'instagram', 'tiktok', 'reels'] },
    { term: 'journalism & news', k: ['journalis', 'news', 'press'] },
    { term: 'misinformation & WhatsApp politics', k: ['misinformation', 'whatsapp', 'fake news', 'disinformation'] },
    { term: 'audiences & fandom', k: ['audience', 'fandom', 'fans'] },
    { term: 'media industries', k: ['industry', 'industries', 'ott', 'streaming'] },
  ] },
  { field: 'Internet & platform studies', topics: [
    { term: 'content moderation & caste speech', k: ['moderation', 'hate speech', 'caste speech', 'takedown'] },
    { term: 'platform governance', k: ['platform', 'governance', 'regulation', 'policy'] },
    { term: 'algorithms & visibility', k: ['algorithm', 'visibility', 'recommend'] },
    { term: 'digital labour', k: ['labour', 'labor', 'gig', 'work'] },
    { term: 'dating apps & intimacy', k: ['dating', 'intimacy', 'tinder', 'bumble'] },
  ] },
  { field: 'Memory & history', topics: [
    { term: 'Partition memory online', k: ['partition', 'memory online', 'digital memory'] },
    { term: 'oral history', k: ['oral history', 'testimony', 'interview'] },
    { term: 'archives & community archives', k: ['archive', 'archival'] },
  ] },
  { field: 'Sociology & anthropology', topics: [
    { term: 'urban informality', k: ['urban', 'city', 'slum', 'informal'] },
    { term: 'social movements', k: ['movement', 'protest', 'activis'] },
    { term: 'ethnography of media', k: ['ethnograph', 'fieldwork'] },
  ] },
];

/** Reasons offered in the dismiss dialog, and the reweight each one triggers. */
export const dismissReasons = [
  { id: 'too_expensive', label: 'Too expensive', emoji: '💸', effect: 'Lowers your cost ceiling and weights affordability higher.' },
  { id: 'wrong_stage', label: 'Wrong career stage', emoji: '🎓', effect: 'Tightens the eligibility filter on career stage.' },
  { id: 'off_topic', label: 'Off topic', emoji: '🎯', effect: 'Reduces the weight of the topics this one matched on.' },
  { id: 'bad_timing', label: 'Bad timing', emoji: '📅', effect: 'Down-weights months outside your availability.' },
  { id: 'visa_infeasible', label: 'Visa is not realistic', emoji: '🛂', effect: 'Prefers destinations with lighter visa requirements.' },
  { id: 'not_prestigious', label: 'Not worth it for my CV', emoji: '🏛', effect: 'Weights venue standing higher.' },
  { id: 'other', label: 'Something else', emoji: '💬', effect: 'Logged for review; no automatic reweight.' },
];
