/**
 * Grapevine prototype — data layer.
 *
 * Example shortlists are REAL skill output, not hand-written fixtures: corpus.js is
 * generated by scripts/build-feed.mjs from corpus/ (produced by the skills in
 * .claude/skills/). This file adds the UI-only vocabularies.
 */

import { EXAMPLES, GATHERED_AT, profile, opportunities, heldBack, FX, meta } from './corpus.js';

export { EXAMPLES, GATHERED_AT, profile, opportunities, heldBack, FX, meta };

export const TODAY = new Date(new Date().toISOString().slice(0, 10) + 'T00:00:00Z');

/** Steps shown in the "finding opportunities" screen, with the real counts from that example's skill run. */
export const pipelineFor = (m, currency) => [
  { label: 'Reading your interests', detail: `Your topics, plus ${m.adjacent} nearby fields worth searching` },
  { label: 'Searching your field and the ones next to it', detail: `${m.candidates || m.extracted} possibilities found` },
  { label: 'Reading each call page', detail: `${m.extracted} checked for dates, fees and who can apply` },
  { label: 'Working out cost and funding', detail: `Costs in ${currency} · ${m.funding} ways to pay for it` },
  { label: 'Ranking by what you care about', detail: 'Using the goals you picked' },
  { label: 'Double-checking the dates', detail: `${m.grounded_pass} of ${m.grounded_total} matched the source page` },
];
export const pipeline = pipelineFor(meta, profile.currency);

/** What someone might want out of an opportunity. Each goal shifts the priority weights. */
export const GOALS = [
  { id: 'networking', label: 'Meet people', sub: 'Who you would meet', emoji: '🤝' },
  { id: 'publication', label: 'Get published', sub: 'A route into print', emoji: '📄' },
  { id: 'visibility', label: 'A well-known conference', sub: 'A line that counts on a CV', emoji: '🏛' },
  { id: 'low_cost', label: 'Keep it affordable', sub: 'Cost and visa matter most', emoji: '💸' },
  { id: 'feedback', label: 'Feedback on my work', sub: 'Workshops, respondents', emoji: '💬' },
];

/** Country names for the "Based in" / "Passport" search-as-you-type fields. English short names, UN member states + a few common territories. */
export const COUNTRIES = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
  'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
  'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi',
  'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
  'Comoros', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia',
  'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic',
  'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia',
  'Fiji', 'Finland', 'France',
  'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
  'Haiti', 'Honduras', 'Hong Kong', 'Hungary',
  'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
  'Jamaica', 'Japan', 'Jordan',
  'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait', 'Kyrgyzstan',
  'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
  'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius',
  'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
  'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway',
  'Oman',
  'Pakistan', 'Palau', 'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Puerto Rico',
  'Qatar',
  'Republic of the Congo', 'Romania', 'Russia', 'Rwanda',
  'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
  'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
  'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain',
  'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria',
  'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago',
  'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu',
  'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
  'Vanuatu', 'Vatican City', 'Venezuela', 'Vietnam',
  'Yemen',
  'Zambia', 'Zimbabwe',
];

/** Browsable topic list for onboarding, grouped by field. `k` = keywords matched in free text. */
export const topicVocabulary = [
  { field: 'South Asian studies', topics: [
    { term: 'caste & digital media', k: ['caste', 'dalit', 'bahujan', 'jati'] },
    { term: 'Dalit & Bahujan counterpublics', k: ['dalit', 'bahujan', 'ambedkar', 'counterpublic'] },
    { term: 'Partition memory', k: ['partition', '1947'] },
    { term: 'South Asian diaspora', k: ['diaspora', 'migrant', 'nri'] },
    { term: 'Hindi & regional-language cinema', k: ['cinema', 'bollywood', 'film', 'tamil', 'telugu'] },
    { term: 'gender & sexuality in South Asia', k: ['gender', 'queer', 'feminis', 'sexuality'] },
    { term: 'religion & politics in India', k: ['hindutva', 'religio', 'communal', 'muslim'] },
  ] },
  { field: 'Media & communication', topics: [
    { term: 'creator cultures & influencers', k: ['creator', 'influencer', 'youtube', 'instagram', 'tiktok', 'reels'] },
    { term: 'journalism & news', k: ['journalis', 'news', 'press'] },
    { term: 'misinformation & WhatsApp politics', k: ['misinformation', 'whatsapp', 'fake news', 'disinformation'] },
    { term: 'audiences & fandom', k: ['audience', 'fandom', 'fans'] },
    { term: 'media industries', k: ['industry', 'industries', 'ott', 'streaming'] },
  ] },
  { field: 'Internet, AI & platforms', topics: [
    { term: 'content moderation & caste speech', k: ['moderation', 'hate speech', 'caste speech', 'takedown'] },
    { term: 'AI and data labour', k: [' ai ', 'artificial intelligence', 'data label', 'annotation', 'click-work', 'ghost work'] },
    { term: 'platform governance', k: ['platform', 'governance', 'regulation', 'policy'] },
    { term: 'algorithms & visibility', k: ['algorithm', 'visibility', 'recommend'] },
    { term: 'digital labour', k: ['labour', 'labor', 'gig', 'work'] },
    { term: 'dating apps & intimacy', k: ['dating', 'intimacy', 'tinder', 'bumble'] },
  ] },
  { field: 'Memory, history & archives', topics: [
    { term: 'Partition memory online', k: ['partition', 'memory online', 'digital memory'] },
    { term: 'oral history', k: ['oral history', 'testimony', 'interview'] },
    { term: 'archives & community archives', k: ['archive', 'archival'] },
  ] },
  { field: 'Society, health & environment', topics: [
    { term: 'climate & migration', k: ['climate', 'flood', 'migration', 'displace'] },
    { term: 'public health & gender', k: ['health', 'maternal', 'clinic', 'care'] },
    { term: 'education policy', k: ['education', 'school', 'exam', 'curriculum'] },
    { term: 'urban informality', k: ['urban', 'city', 'slum', 'informal'] },
    { term: 'social movements', k: ['movement', 'protest', 'activis'] },
  ] },
  { field: 'Film & culture', topics: [
    { term: 'queer cinema', k: ['queer', 'lgbt', 'film festival'] },
    { term: 'popular music & zines', k: ['music', 'zine', 'popular culture'] },
  ] },
];

/** Reasons offered in the dismiss dialog, and the reweight each one triggers. */
export const dismissReasons = [
  { id: 'too_expensive', label: 'Too expensive', emoji: '💸', effect: 'Lowers your cost ceiling and weights affordability higher.' },
  { id: 'wrong_stage', label: 'Wrong career stage', emoji: '🎓', effect: 'Tightens the eligibility filter on career stage.' },
  { id: 'off_topic', label: 'Off topic', emoji: '🎯', effect: 'Reduces the weight of the topics this one matched on.' },
  { id: 'bad_timing', label: 'Bad timing', emoji: '📅', effect: 'Down-weights months outside your availability.' },
  { id: 'visa_infeasible', label: 'Visa is not realistic', emoji: '🛂', effect: 'Prefers destinations with lighter visa requirements.' },
  { id: 'not_prestigious', label: 'Not worth it for my CV', emoji: '🏛', effect: 'Gives well-respected conferences and journals more weight.' },
  { id: 'other', label: 'Something else', emoji: '💬', effect: 'Logged for review; no automatic reweight.' },
];
